### ISSUE TITLE
Point to UBKG ontology-api PROD instance for Data Sankey

### ISSUE THREAD

**Issue by yuanzhou** [hubmapconsortium/documentation#22]
Changes made via PR https://github.com/hubmapconsortium/documentation/pull/21 used the DEV instance URL, change to PROD once we release the UBKG Neo4j 9/13 version and the latest hs-ontology-api.

FYI @shirey

**Comment by shirey** [comment]
Complete and released for both HuBMAP and SenNet (FYI @maxsibilla) Sanky
