### ISSUE TITLE
Documentation for `param-search` feature

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/documentation#4]
Create full documentation on the software.docs site for the new parameterized search feature which:
 - Explains how to use the new /param-search/<entity-type> endpoint
 - Fully documents the schemata for the entities types supported as a way of documenting the available, searchable attributes. This should explain the construction of multilevel attributes, for example if searching in Sample space the attribute donor.protocol_url is constructed from the top level Sample attribute donor (which points to the Donor schema), then protocol_url attribute from Donor.

**Comment by yuanzhou** [comment]
Oops, closed by mistake.
